### ISSUE TITLE
Investigate 401 response on delivery reports 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications-sms#48]
### Description

After July 9th we have only responses 401 on attempts to send delivery reports. Corresponds with prod deploy. Should be investigated. 

### Additional Information

- Cannot see this same error in TT02. 

### Conclusion

- updated credentials.

**Comment by acn-sbuad** [comment]
https://github.com/microsoft/azure-pipelines-agent/issues/4337

**Comment by olebhansen** [comment]
Platform is following up in https://github.com/Altinn/altinn-platform/issues/875

**Comment by acn-sbuad** [comment]
Password updated in production closing issue. Future followup should be through the platform issue
